# Generated by Django 5.2.6 on 2025-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Become a Member', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(default='Join Now', max_length=50)),
                ('button_link', models.URLField(blank=True, help_text='URL to membership form or contact page', null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='membership/')),
            ],
            options={
                'verbose_name': 'Membership Section',
                'verbose_name_plural': 'Membership Section',
            },
        ),
    ]
