# Generated by Django 5.2.6 on 2025-09-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyNelihaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='WHY NELIHA', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='why_neliha/')),
            ],
            options={
                'verbose_name': 'Why NELIHA Section',
                'verbose_name_plural': 'Why NELIHA Section',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
